version: "3.7"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-restaurante}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/New_York
      PGTZ: America/New_York
    volumes:
      - chefwell_dbdata:/var/lib/postgresql/data
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr  # CRITICAL: Allows Prisma to connect properly
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    environment:
      TZ: America/New_York
    volumes:
      - chefwell_redis:/data
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ${DOCKER_REGISTRY:-r.chatwell.pro}/chefwell-backend:${IMAGE_TAG:-latest}
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-restaurante}?schema=public

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}

      # Storage
      STORAGE_PROVIDER: ${STORAGE_PROVIDER:-local}
      LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH:-./uploads}
      LOCAL_STORAGE_BASE_URL: https://${BACKEND_DOMAIN}/uploads

      # AWS S3 / MinIO
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION:-us-east-1}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE:-false}

      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}

      # Application
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: ${FRONTEND_URL}
      TZ: America/New_York
    volumes:
      - chefwell_uploads:/app/uploads
    networks:
      - network_public
    depends_on:
      - postgres
      - redis
    deploy:
      mode: replicated
      replicas: ${BACKEND_REPLICAS:-2}
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.chefwell-backend.rule=Host(`${BACKEND_DOMAIN}`)
        - traefik.http.routers.chefwell-backend.entrypoints=websecure
        - traefik.http.routers.chefwell-backend.tls.certresolver=letsencryptresolver
        - traefik.http.services.chefwell-backend.loadbalancer.server.port=3000
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ${DOCKER_REGISTRY:-r.chatwell.pro}/chefwell-frontend:${IMAGE_TAG:-latest}
    environment:
      VITE_API_URL: https://${BACKEND_DOMAIN}
      TZ: America/New_York
    networks:
      - network_public
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: ${FRONTEND_REPLICAS:-2}
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.chefwell-frontend.rule=Host(`${FRONTEND_DOMAIN}`)
        - traefik.http.routers.chefwell-frontend.entrypoints=websecure
        - traefik.http.routers.chefwell-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.chefwell-frontend.loadbalancer.server.port=80
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  network_public:
    external: true
    name: network_public

volumes:
  chefwell_dbdata:
    external: true
  chefwell_uploads:
    external: true
  chefwell_redis:
    external: true
